#!/bin/sh
#SBATCH --job-name=contrastive        
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --gres=gpu:1            # Number of GPUs (per node)
#SBATCH -p it-hpc                     # Use the gpu partition
#SBATCH --mem=200GB                  # Real mem
#SBATCH --nodelist=gpu80-1               # Time limit in D-HH:MM``

python linear_probe.py
