#!/bin/sh
#SBATCH --job-name=contrastive        
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --gres=gpu:1           # Number of GPUs (per node)
#SBATCH -p cscc-gpu-p                     # Use the gpu partition
#SBATCH -q cscc-gpu-qos                      # Number of tasks per array

python linear_probe.py
