dataset: voc2007 #['imagenet1k', 'tiny_imagenet', 'voc2007', 'caltech101']
N_values: [2, 4] # if -1 the entire training dataset gets evaluated 
pretrained_path: /home/emilio.villa/nlp_playground/CV_PTTs/trained_backbones_stage2/s1-rot-s2-simclr.pth
experiment_savename : rn50_voc2007_s1-rot-s2-simclr
frozen_backbone: true
batch_size : 1024 ##batch size for feature extractor
batch_size_linear_layer: 64
learning_rate: 0.001
max_epochs: 10

lr_max_iterations: 2000

output_folder: /home/emilio.villa/nlp_playground/CV_PTTs/jigsaw/probe_output_stage2/final_experiments

K_values: null # if -1 the entire training dataset gets evaluated
p_reduction : 1.0
