#!/bin/sh
#SBATCH --job-name=10-cal        
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --gres=gpu:1            # Number of GPUs (per node)
#SBATCH -p cscc-gpu-p                     # Use the gpu partition
#SBATCH -q cscc-gpu-qos     
#SBATCH --exclude=gpu-56

hostname
python finetune.py -c '10' -t