#!/bin/sh
#SBATCH --job-name=7-tiny        
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --gres=gpu:1            # Number of GPUs (per node)
#SBATCH -p cscc-gpu-p                     # Use the gpu partition
#SBATCH -q cscc-gpu-qos  
#SBATCH --exclude=gpu-01   

hostname
python finetune.py -c '7' -t