#!/bin/sh
#SBATCH --job-name=eval
#SBATCH --output=eval.out      
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --gres=gpu:1            # Number of GPUs (per node)
#SBATCH -p cscc-gpu-p                     # Use the gpu partition
#SBATCH -q cscc-gpu-qos     

echo "6"
python finetune.py -c 'full_ft'

for i in "1" "3" "4" "5" "6" "7" "8"
do
    echo $i
    python finetune.py -c $i
done