#!/bin/sh
#SBATCH --job-name=8-voc        
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --gres=gpu:1            # Number of GPUs (per node)
#SBATCH -p cscc-gpu-p                     # Use the gpu partition
#SBATCH -q cscc-gpu-qos     

hostname
python finetune.py -c '8' -t