hf_access_token: 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
dataset_download_path: /l/users/karima.kadaoui/.cache/huggingface/datasets ## dir to download datasets
ptt_dataset_name: ILSVRC/imagenet-1k
training_data_proportion: 0.3 #30% of ImageNet1k
rotation_architecture: resnet
seed: 42
epochs: 100
log_each: 100
batch_size: 64
optimizer: sgd
optim_lr: 0.001
optim_momentum: 0.9
optim_decay: 0.0001
checkpoint_path: null #in case we are reloading an old checkpoint
backbone_weights_path: null #if provided, path to resnet state_dict to initialize the model (for training from a different PTT)
experiment_name: rotation_resnet50
savedir: /l/users/karima.kadaoui/Classes/CV801/ckpts/
results_savedir: 'output/'